standardize vars: global meta-vars should be dunders; other global/env vars should be all caps (unless dictated otherwise, re: color vars); 'private' function ars should be prefixed with '__func_name_' (no trailing underscores)

diff --git a/templates/shell-script b/templates/shell-script
--- a/templates/shell-script
+++ b/templates/shell-script
@@ -29,7 +29,7 @@
 #-- Variables which are meta for the script should be dunders (__varname__)
 #-- TODO: UPDATE meta vars
 __version__='{{ version|default("TODO: CHANGEME", true) }}' #: current version
-__revised__='20180403-103904' #: date of most recent revision
+__revised__='20180403-105823' #: date of most recent revision
 __contact__='{{ contact_name|default("TODO: CHANGEME", true) }} <{{ contact_email|default("TODO: CHANGEME", true) }}>' #: primary contact for support/?'s
 __synopsis__='{{ script_synopsis|default("TODO: CHANGEME", true) }}'
 __description__="
@@ -67,16 +67,16 @@ _usage_options() {
     #:
     #: Lists options usign format passed to it.
     #:
-    #: :param str strfmt_option: The format to use.
+    #: :param str option_strfmt: The format to use.
     #:"""
     #-- TODO: UPDATE option list.
-    strfmt_option="${1}"
+    __usage_option_strfmt="${1}"
     #-- We are using a variable to format data in printf
     # shellcheck disable=2059
-    printf "${strfmt_option}" '--help, -h' 'Dislay this help'
+    printf "${__usage_option_strfmt}" '--help, -h' 'Dislay this help'
     #-- We are using a variable to format data in printf
     # shellcheck disable=2059
-    printf "${strfmt_option}" '--version ' 'Display version'
+    printf "${__usage_option_strfmt}" '--version ' 'Display version'
 }
 
 #==============================================================================
@@ -113,14 +113,14 @@ _usage_rest() {
     #:
     #:"""
     # {% raw %}
-    char="%${#__cononical_name__}s" # {% endraw %}
+    __usage_rest_char="%${#__cononical_name__}s" # {% endraw %}
     #-- We are using a variable to format data in printf
     # shellcheck disable=2059
-    printf "${char}\\n" | tr " " "="
+    printf "${__usage_rest_char}\\n" | tr " " "="
     printf '%s\n' "${__cononical_name__}"
     #-- We are using a variable to format data in printf
     # shellcheck disable=2059
-    printf "${char}\\n" | tr " " "="
+    printf "${__usage_rest_char}\\n" | tr " " "="
     printf '\n'
     printf 'Synopsis\n'
     printf '%s\n\n' '--------'
@@ -164,7 +164,11 @@ _version() {
 # Get logger() settings from ENV
 LOGGER_FILE=${LOGGER_FILE:="nil"}
 LOGGER_DSF=${LOGGER_DSF:="%Y%m%d-%H%M%S"}
-LOGGER_FILE_SET='false'
+if [ "${__logger_file_set__}" = "nil" ]; then
+    __logger_file_set__='false'
+else
+    __logger_file_set__='true'
+fi
 case $(printf '%s' "${LOGGER_LVL:="info"}" | tr '[:upper:]' '[:lower:]') in
     debug)          LOGGER_LVL=10 ;;
     info)           LOGGER_LVL=20 ;;
@@ -188,32 +192,32 @@ logger() {
     #:     code here. See: https://github.com/nk412/tinylogger
     #:"""
     case $(printf '%s' "${1}") in 
-        debug)          action_tag='DEBUG'    ; log_level_th=10 ;;
-        info)           action_tag='INFO'     ; log_level_th=20 ;;
-        warn|warning)   action_tag='WARNING'  ; log_level_th=30 ;;
-        error)          action_tag='ERROR'    ; log_level_th=40 ;;
-        crit|critical)  action_tag='CRITICAL' ; log_level_th=50 ;;
-        *)              action_tag='UNKNOWN'  ; log_level_th=0 ;;
+        debug)          __logger_action_tag='DEBUG'    ; __logger_log_level_th=10 ;;
+        info)           __logger_action_tag='INFO'     ; __logger_log_level_th=20 ;;
+        warn|warning)   __logger_action_tag='WARNING'  ; __logger_log_level_th=30 ;;
+        error)          __logger_action_tag='ERROR'    ; __logger_log_level_th=40 ;;
+        crit|critical)  __logger_action_tag='CRITICAL' ; __logger_log_level_th=50 ;;
+        *)              __logger_action_tag='UNKNOWN'  ; __logger_log_level_th=0 ;;
     esac
     shift
 
-    if [ "${LOGGER_FILE_SET}" = "true" ]; then
+    if [ "${__logger_file_set__}" = "true" ]; then
         printf '%s [%s]: %s\n' "$(date "+${LOGGER_DSF}")" \
-                               "${action_tag}" "${@}" 1>&3
+                               "${__logger_action_tag}" "${@}" 1>&3
     fi
 
-    if [ "${LOGGER_LVL}" -le "${log_level_th}" ]; then
-        if [ "${script_debug}" = true ]; then
+    if [ "${LOGGER_LVL}" -le "${__logger_log_level_th}" ]; then
+        if [ "${__script_debug__}" = true ]; then
             printf '%s %-10s ' "${cf_blue}$(date "+${LOGGER_DSF}")" \
-                               "${action_tag}${c_reset}"
+                               "${__logger_action_tag}${c_reset}"
         fi
-        if [ "${log_level_th}" -le 10 ]; then
+        if [ "${__logger_log_level_th}" -le 10 ]; then
             printf '%sdebug: %s%s\n' "${cf_green}" "${@}" "${c_reset}"
-        elif [ "${log_level_th}" -le 20 ]; then
+        elif [ "${__logger_log_level_th}" -le 20 ]; then
             printf '%s%s%s\n' "${cf_white}" "${@}" "${c_reset}"
-        elif [ "${log_level_th}" -le 30 ]; then
+        elif [ "${__logger_log_level_th}" -le 30 ]; then
             printf '%sWarning: %s%s\n' "${cf_yellow}" "${@}" "${c_reset}" 1>&2
-        elif [ "${log_level_th}" -le 40 ]; then
+        elif [ "${__logger_log_level_th}" -le 40 ]; then
             printf '%sError: %s%s\n' "${cf_magenta}" "${@}" ""${c_reset} 1>&2
         else
             printf '%sCRITICAL: %s%s\n' "${cf_red}" "${@}" "${c_reset}" 1>&2
@@ -265,14 +269,14 @@ set_value() {
     #: :param str key:    Key to create/modify
     #: :param str value:  Value to set key to
     #:"""
-    SET_VALUE_FILE="${1}"
-    SET_VALUE_KEY="${2}"
-    SET_VALUE_VALUE="${3}"
-    if [ ! -e "${SET_VALUE_FILE}" ]; then touch "${SET_VALUE_FILE}" || return "${?}"; fi
-    if grep -q "^${SET_VALUE_KEY}=" "${SET_VALUE_FILE}"; then
-        sed -i "s/^${SET_VALUE_KEY}=.*/${SET_VALUE_KEY}='${SET_VALUE_VALUE}'/" "${SET_VALUE_FILE}" || return "${?}"
+    __set_value_file="${1}"
+    __set_value_key="${2}"
+    __set_value_value="${3}"
+    if [ ! -e "${__set_value_file}" ]; then touch "${__set_value_file}" || return "${?}"; fi
+    if grep -q "^${__set_value_key}=" "${__set_value_file}"; then
+        sed -i "s/^${__set_value_key}=.*/${__set_value_key}='${__set_value_value}'/" "${__set_value_file}" || return "${?}"
     else
-        printf '%s=%s\n' "${SET_VALUE_KEY}" "'${SET_VALUE_VALUE}'" >> "${SET_VALUE_FILE}" || return "${?}"
+        printf '%s=%s\n' "${__set_value_key}" "'${__set_value_value}'" >> "${__set_value_file}" || return "${?}"
     fi
 
     return 0
@@ -294,7 +298,7 @@ exit_error() {
     #:"""
     printf '%s: %s\n' "${cf_red}${__cononical_name__}" \
                       "${c_bold}${2}${c_reset}" 1>&2
-    if [ "${LOGGER_FILE_SET}" = "true" ]; then
+    if [ "${__logger_file_set__}" = "true" ]; then
         printf '%s [EXIT]: %s\n' "$(date "+${LOGGER_DSF}")" "${2}" 1>&3
         printf "Log file created: %s\n" "${LOGGER_FILE}"
         exec 3>&-
@@ -322,14 +326,14 @@ exit_clean() {
     #:
     #: Clean up everything and exit gracefully
     #:"""
-    [ "${script_debug}" = true ] && {
+    [ "${__script_debug__}" = true ] && {
         set +o xtrace
-        script_debug=false
+        __script_debug__=false
         printf '%s\n' '------ end ------'
     }
 
     trap - INT TERM HUP
-    if [ "${LOGGER_FILE_SET}" = "true" ]; then
+    if [ "${__logger_file_set__}" = "true" ]; then
         printf '%s [EXIT]: Script finished.\n' "$(date "+${LOGGER_DSF}")" 1>&3
         logger info "Log file created: ${LOGGER_FILE}"
         exec 3>&-
@@ -354,12 +358,12 @@ _init() {
     #--------------------------------------------------------------------------
     #-- Create log file if needed AND we didn't do it in --debug check
     #--------------------------------------------------------------------------
-    if [ "${LOGGER_FILE}" != "nil" ] && [ "${LOGGER_FILE_SET}" != "true" ]; then
+    if [ "${LOGGER_FILE}" != "nil" ] && [ "${__logger_file_set__}" != "true" ]; then
         if [ -f "${LOGGER_FILE}" ] ; then
             mv "${LOGGER_FILE}" "${LOGGER_FILE}"."$(date +%Y%m%d-%H%M%S)"
         fi
         exec 3<> "${LOGGER_FILE}" || exit 1
-        LOGGER_FILE_SET='true'
+        __logger_file_set__='true'
     fi
     #--------------------------------------------------------------------------
 }
@@ -372,15 +376,15 @@ if [ "${*#*--debug}" != "${*}" ]; then
             mv "${LOGGER_FILE}" "${LOGGER_FILE}"."$(date +%Y%m%d-%H%M%S)"
         fi
         exec 3<> "${LOGGER_FILE}" || exit 1
-        LOGGER_FILE_SET='true'
+        __logger_file_set__='true'
     fi
-    script_debug='true'
+    __script_debug__='true'
     LOGGER_LVL=10
     _debug_info "$@"
     #-- Only do full shell trace if external DEBUG var set to full
     [ "${DEBUG}" = 'full' ] && set -o xtrace
 else
-    script_debug=false
+    __script_debug__=false
 fi
 
 #-- Some default settings
