bug in detecting if logger file is set; tweak debug output (repush cuz wtf fd up); re-arrange functions so that 'private' ones come first, others are in order of usage

diff --git a/templates/shell-script b/templates/shell-script
--- a/templates/shell-script
+++ b/templates/shell-script
@@ -29,7 +29,7 @@
 #-- Variables which are meta for the script should be dunders (__varname__)
 #-- TODO: UPDATE meta vars
 __version__='{{ version|default("TODO: CHANGEME", true) }}' #: current version
-__revised__='20180403-123512' #: date of most recent revision
+__revised__='20180403-125413' #: date of most recent revision
 __contact__='{{ contact_name|default("TODO: CHANGEME", true) }} <{{ contact_email|default("TODO: CHANGEME", true) }}>' #: primary contact for support/?'s
 __synopsis__='{{ script_synopsis|default("TODO: CHANGEME", true) }}'
 __description__="
@@ -50,7 +50,7 @@ __template_version__='1.10.1'             #: version of template file used
 # shellcheck disable=2034
 __docformat__='reStructuredText en'      #: attempted style for documentation
 __basename__="${0}" #: name script run as
-__logger_file_set__='false'
+__logger_file_set__='false' #: Flag notifying if a file is set for logger
 #------------------------------------------------------------------------------
 #-- use colors if they are set in the ENV
 cf_black=${cf_black:=''}   ; cf_white=${cf_white:=''}
@@ -61,25 +61,6 @@ cf_cyan=${cf_cyan:=''}     ; cf_green=${cf_green:=''}
 c_bold=${c_bold:=''}       ; c_reset=${c_reset:=''}
 c_undr=${c_undr:=''}       ; c_hide=${c_hide:=''}
 c_blik=${c_blik:=''}       ; c_revr=${c_revr:=''}
-#==============================================================================
-_usage_options() {
-    #:"""
-    #: .. function:: _usage_options()
-    #:
-    #: Lists options usign format passed to it.
-    #:
-    #: :param str option_strfmt: The format to use.
-    #:"""
-    #-- TODO: UPDATE option list.
-    __usage_option_strfmt="${1}"
-    #-- We are using a variable to format data in printf
-    # shellcheck disable=2059
-    printf "${__usage_option_strfmt}" '--help, -h' 'Dislay this help'
-    #-- We are using a variable to format data in printf
-    # shellcheck disable=2059
-    printf "${__usage_option_strfmt}" '--version ' 'Display version'
-}
-
 #==============================================================================
 _usage() {
     #:"""
@@ -103,6 +84,25 @@ _usage() {
     printf '%s, part of %s. Project home: %s\n' "${__cononical_name__}" \
                                                 "${__project_name__}" \
                                                 "${__project_home__}"
+}
+
+#==============================================================================
+_usage_options() {
+    #:"""
+    #: .. function:: _usage_options()
+    #:
+    #: Lists options usign format passed to it.
+    #:
+    #: :param str option_strfmt: The format to use.
+    #:"""
+    #-- TODO: UPDATE option list.
+    __usage_option_strfmt="${1}"
+    #-- We are using a variable to format data in printf
+    # shellcheck disable=2059
+    printf "${__usage_option_strfmt}" '--help, -h' 'Dislay this help'
+    #-- We are using a variable to format data in printf
+    # shellcheck disable=2059
+    printf "${__usage_option_strfmt}" '--version ' 'Display version'
 }
 
 #==============================================================================
@@ -159,6 +159,53 @@ _version() {
     #-- TODO: UPDATE license - a boilerplate notice should go here as well
     # printf '%s\n' "${__copyright__}"
     # printf '%s\n' "${__license__}"
+}
+
+#==============================================================================
+_debug_info() {
+    #:"""
+    #: .. function:: _debug_info()
+    #:
+    #: Provides meta info for debug-level output
+    #:
+    #: .. note::
+    #:     We set script_path here to avoid calling cd/dirname/pwd when not really needed
+    #:"""
+    # shellcheck disable=SC1007
+    script_path="$(CDPATH= cd -- "$(dirname -- "${0}")" && pwd )"
+
+    logger debug "Cononical: ${__cononical_name__}"
+    logger debug "Abs Path:  ${script_path}/${__basename__}"
+    logger debug "Args List: ${*}"
+    logger debug "Version:   ${__version__}"
+    logger debug "md5sum:    $(md5sum "${__basename__}")"
+    logger debug "Created:   ${__created__}"
+    logger debug "Revised:   ${__revised__}"
+    logger debug "Coder(s):  ${__author__}"
+    logger debug "Contact:   ${__contact__}"
+    logger debug "Project:   ${__project_name__}"
+    logger debug "Project Home: ${__project_home__}"
+    logger debug "Template Version: ${__template_version__}"
+    logger debug "System:    $(uname -orv)"
+    logger debug "Hostname:  $(hostname)"
+    logger debug "[re]uid:   $(id -ur)/$(id -u)"
+    logger debug "PID/PPID:  /${PPID}"
+    logger debug '-----------------'
+    logger debug '----- start -----'
+    logger debug '-----------------'
+}
+
+#==============================================================================
+_exit_trap() {
+    #:"""
+    #: .. function:: exit_trap()
+    #:
+    #: On terminal traps, run this before exit_error
+    #:
+    #: :param int trap_line: Line number trap caught on
+    #: :param str trap_name: Short name of trap
+    #:"""
+    exit_error "${?}" "caught trap ${2} at line ${1}; exiting"
 }
 
 #==============================================================================
@@ -223,37 +270,51 @@ logger() {
 }
 
 #==============================================================================
-_debug_info() {
+exit_error() {
     #:"""
-    #: .. function:: _debug_info()
+    #: .. function:: exit_error()
     #:
-    #: Provides meta info for debug-level output
+    #: Report error and exit
     #:
+    #: :param int error_number:  Number to use for Exit Code
+    #: :param str error_string:  Short description of error
     #: .. note::
-    #:     We set script_path here to avoid calling cd/dirname/pwd when not really needed
+    #:     You may want to use ${LINENO} in the string this is called with.
+    #: .. warning::
+    #:     This function exits the script
     #:"""
-    # shellcheck disable=SC1007
-    script_path="$(CDPATH= cd -- "$(dirname -- "${0}")" && pwd )"
+    printf '%s: %s\n' "${cf_red}${__cononical_name__}" \
+                      "${c_bold}${2}${c_reset}" 1>&2
+    if [ "${__logger_file_set__}" = "true" ]; then
+        printf '%s [EXIT]: %s\n' "$(date "+${LOGGER_DSF}")" "${2}" 1>&3
+        printf "Log file created: %s\n" "${LOGGER_FILE}"
+        exec 3>&-
+    fi
+    exit "${1}"
+}
 
-    logger debug "Cononical: ${__cononical_name__}"
-    logger debug "Abs Path:  ${script_path}/${__basename__}"
-    logger debug "Args List: ${*}"
-    logger debug "Version:   ${__version__}"
-    logger debug "md5sum:    $(md5sum "${__basename__}")"
-    logger debug "Created:   ${__created__}"
-    logger debug "Revised:   ${__revised__}"
-    logger debug "Coder(s):  ${__author__}"
-    logger debug "Contact:   ${__contact__}"
-    logger debug "Project:   ${__project_name__}"
-    logger debug "Project Home: ${__project_home__}"
-    logger debug "Template Version: ${__template_version__}"
-    logger debug "System:    $(uname -orv)"
-    logger debug "Hostname:  $(hostname)"
-    logger debug "[re]uid:   $(id -ur)/$(id -u)"
-    logger debug "PID/PPID:  /${PPID}"
-    logger debug ''
-    logger debug '----- start -----'
-    logger debug ''
+#==============================================================================
+exit_clean() {
+    #:"""
+    #: .. function:: exit_clean()
+    #:
+    #: Clean up everything and exit gracefully
+    #:"""
+    [ "${__script_debug__}" = true ] && {
+        set +o xtrace
+        logger debug '-----------------'
+        logger debug '------ end ------'
+        logger debug '-----------------'
+        __script_debug__=false
+    }
+
+    trap - INT TERM HUP
+    if [ "${__logger_file_set__}" = "true" ]; then
+        printf '%s [EXIT]: Script finished.\n' "$(date "+${LOGGER_DSF}")" 1>&3
+        logger info "Log file created: ${LOGGER_FILE}"
+        exec 3>&-
+    fi
+    exit 0
 }
 
 #==============================================================================
@@ -281,68 +342,7 @@ set_value() {
 }
 
 #==============================================================================
-exit_error() {
-    #:"""
-    #: .. function:: exit_error()
-    #:
-    #: Report error and exit
-    #:
-    #: :param int error_number:  Number to use for Exit Code
-    #: :param str error_string:  Short description of error
-    #: .. note::
-    #:     You may want to use ${LINENO} in the string this is called with.
-    #: .. warning::
-    #:     This function exits the script
-    #:"""
-    printf '%s: %s\n' "${cf_red}${__cononical_name__}" \
-                      "${c_bold}${2}${c_reset}" 1>&2
-    if [ "${__logger_file_set__}" = "true" ]; then
-        printf '%s [EXIT]: %s\n' "$(date "+${LOGGER_DSF}")" "${2}" 1>&3
-        printf "Log file created: %s\n" "${LOGGER_FILE}"
-        exec 3>&-
-    fi
-    exit "${1}"
-}
-
-#==============================================================================
-_exit_trap() {
-    #:"""
-    #: .. function:: exit_trap()
-    #:
-    #: On terminal traps, run this before exit_error
-    #:
-    #: :param int trap_line: Line number trap caught on
-    #: :param str trap_name: Short name of trap
-    #:"""
-    exit_error "${?}" "caught trap ${2} at line ${1}; exiting"
-}
-
-#==============================================================================
-exit_clean() {
-    #:"""
-    #: .. function:: exit_clean()
-    #:
-    #: Clean up everything and exit gracefully
-    #:"""
-    [ "${__script_debug__}" = true ] && {
-        set +o xtrace
-        logger debug ''
-        logger debug '------ end ------'
-        logger debug ''
-        __script_debug__=false
-    }
-
-    trap - INT TERM HUP
-    if [ "${__logger_file_set__}" = "true" ]; then
-        printf '%s [EXIT]: Script finished.\n' "$(date "+${LOGGER_DSF}")" 1>&3
-        logger info "Log file created: ${LOGGER_FILE}"
-        exec 3>&-
-    fi
-    exit 0
-}
-
-#==============================================================================
-_init() {
+init() {
     #:"""
     #: .. function:: init()
     #:
@@ -422,7 +422,7 @@ while [ "${#}" -gt 0 ]; do  # {% endraw %}
     shift
 done
 
-_init
+init
 
 #==============================================================================
 #-- TODO: Do something more interesting here...{#
