bug fix: mis-quote

diff --git a/templates/shell-script b/templates/shell-script
--- a/templates/shell-script
+++ b/templates/shell-script
@@ -29,7 +29,7 @@
 #-- Variables which are meta for the script should be dunders (__varname__)
 #-- TODO: UPDATE meta vars
 __version__='{{ version|default("TODO: CHANGEME", true) }}' #: current version
-__revised__='20181015-152700' #: date of most recent revision
+__revised__='20181114-154739' #: date of most recent revision
 __contact__='{{ contact_name|default("TODO: CHANGEME", true) }} <{{ contact_email|default("TODO: CHANGEME", true) }}>' #: primary contact for support/?'s
 __synopsis__='{{ script_synopsis|default("TODO: CHANGEME", true) }}'
 __description__="
@@ -53,11 +53,12 @@ __license__='{{ software_license|default("TODO: CHANGEME", true) }}'
 __cononical_name__='{{ script_name|default("TODO: CHANGEME", true) }}' #: static name, *NOT* os.path.basename(sys.argv[0])
 __project_name__='{{ project_name|default("TODO: CHANGEME", true) }}'  #: name of overall project, if needed
 __project_home__='{{ project_home|default("TODO: CHANGEME", true) }}'  #: where to find source/documentation
-__template_version__='2.9.0'  #: version of template file used
+__template_version__='2.10.1'  #: version of template file used
 #-- We are not using this variable for now.
 # shellcheck disable=2034
 __docformat__='reStructuredText en'  #: attempted style for documentation
-__basename__="${0}"  #: name script run as
+__basename__="${0}"         #: name script run as
+__original_args__="${*}"    #: capture original arg list before messing with it
 #------------------------------------------------------------------------------
 #-- Load in environment variables, or set defaults
 __default_dsf__=${DEFAULT_TIMESTAMP:="+%Y%m%d-%H%M%S"} #: Default format for 'date' command
@@ -192,9 +193,9 @@ _debug_info() {
 
     logger debug "Cononical: ${__cononical_name__}"
     logger debug "Abs Path:  ${script_path}/${__basename__}"
-    logger debug "Args List: ${*}"
+    logger debug "Args List: ${__original_args__}"
     logger debug "Version:   ${__version__}"
-    logger debug "md5sum:    $(md5sum "${__basename__}")"
+    logger debug "md5sum:    $(md5sum "${__basename__}" 2>&1)"
     logger debug "Created:   ${__created__}"
     logger debug "Revised:   ${__revised__}"
     logger debug "Coder(s):  ${__author__}"
@@ -202,11 +203,14 @@ _debug_info() {
     logger debug "Project:   ${__project_name__}"
     logger debug "Project Home: ${__project_home__}"
     logger debug "Template Version: ${__template_version__}"
-    logger debug "System:    $(uname -orv)"
-    logger debug "Hostname:  $(hostname)"
-    logger debug "Logname:   $(logname)"
-    logger debug "[re]uid:   $(id -ur)/$(id -u)"
+    logger debug "System:    $(uname -orv 2>&1)"
+    logger debug "Hostname:  $(hostname 2>&1)"
+    logger debug "Logname:   ${USERNAME:=$(logname 2>&1)}"
+    logger debug "[re]uid:   $(id -ur 2>&1)/$(id -u 2>&1)"
     logger debug "PID/PPID:  ${$}/${PPID}"
+    if [ -x /bin/pstree ] ; then
+        logger debug "$(/bin/pstree -psu ${$})"
+    fi
     logger debug '-----------------'
     logger debug '----- start -----'
     logger debug '-----------------'
@@ -270,7 +274,7 @@ logger() {
         elif [ "${__logger_log_level_th}" -le 30 ]; then
             printf '%sWarning: %s%s\n' "${cf_yellow}" "${@}" "${c_reset}" 1>&2
         elif [ "${__logger_log_level_th}" -le 40 ]; then
-            printf '%sError: %s%s\n' "${cf_magenta}" "${@}" ""${c_reset} 1>&2
+            printf '%sError: %s%s\n' "${cf_magenta}" "${@}" "${c_reset}" 1>&2
         else
             printf '%sCRITICAL: %s%s\n' "${cf_red}" "${@}" "${c_reset}" 1>&2
         fi
@@ -472,6 +476,7 @@ init() {
         exec 3>&1 || exit 1
         __logger_file_set__='false'
     fi
+    _debug_info
     #--------------------------------------------------------------------------
     return
 }
@@ -535,7 +540,6 @@ while [ "${#}" -gt 0 ]; do  # {% endraw %}
 done
 
 init
-_debug_info "$@"
 
 #==============================================================================
 #-- TODO: Do something more interesting here...{#
